### ISSUE TITLE
Configure login and other options for DapticsClient

### ISSUE THREAD

**Issue by nhpackard** [ProtoLife/daptics-api#10]
Could we have a function that queries for login and password, so that we don't have to have the login info hanging around in the notebook.

**Comment by pzingg** [comment]
Is the suggestion that we add a callback function to the DapticsClient constructor arguments, that if supplied, will be called to obtain the username and password? I can think of three ways to do this:

1. Predefined environment variables (`DAPTICS_HOST`, `DAPTICS_USER`, `DAPTICS_PASSWORD`, `DAPTICS_AUTO_EXPORT_PATH`, `DAPTICS_AUTO_TASK_START`, and `DAPTICS_AUTO_TASK_TIMEOUT`) that would supply these parameters to DapticsClient
2. Credentials JSON config file with `{"host": host, "user": user, "password": password, "auto_export_path": ...}` that would be used to construct DapticsClient 
3. Login callback function argument passed to constructor that would return a `(username, password)` Python tuple.

Or any combination of the above.
