### ISSUE TITLE
ipynb files don't display in github

### ISSUE THREAD

**Issue by nhpackard** [ProtoLife/daptics-api#21]
In python_client there are the ipynb files, e.g. `01_README.ipynb`, etc.  Normally these are displayed by github (in non-executable form).  

For some reason, I can't get them to display, get message 
```
Sorry, something went wrong. Reload?
```
Wonder what's up with that?

Loading those ipynb files might be a good proxy for documentation directly available on the repo.

**Comment by pzingg** [comment]
CNR.
