### ISSUE TITLE
can't connect to api.daptics.api/api

### ISSUE THREAD

**Issue by nhpackard** [ProtoLife/daptics-api#36]
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-3-a2e672235993> in <module>
     27 # The 'connect' method will connect to the API server and obtain the
     28 # GraphQL schema.
---> 29 daptics.connect()

~/Projects/daptics-api/python_client/daptics_client/daptics_client.py in connect(self)
   1036                 verify=self.SSL_CERT_VERIFICATION)
   1037             self.gql = gql.Client(
-> 1038                 transport=http, fetch_schema_from_transport=True)
   1039 
   1040         compat = self.check_api_compatibility()

~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/gql/client.py in __init__(self, schema, introspection, type_def, transport, fetch_schema_from_transport, retries)
     35                 not schema
     36             ), "Cannot fetch the schema from transport if is already provided"
---> 37             introspection = transport.execute(parse(introspection_query)).data
     38         if introspection:
     39             assert (

~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/gql/transport/requests.py in execute(self, document, variable_values, operation_name, timeout)
    122 
    123         if "errors" not in result and "data" not in result:
--> 124             response.raise_for_status()
    125             raise requests.HTTPError(
    126                 "Server did not return a GraphQL result", response=response

~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    939 
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 
    943     def close(self):

HTTPError: 502 Server Error: Bad Gateway for url: https://api.daptics.ai/api

**Comment by nhpackard** [comment]
```
N-Pro:~ n$ curl api.daptics.ai/api
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

```

**Comment by pzingg** [comment]
Daemon restarted. Please try again.
