### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by nhpackard** [ProtoLife/daptics-api#46]
Connection problem.  Certs are valid on spin.protolife.com.  Maybe not getting to the docker image?

---------------------------------------------------------------------------
SSLCertVerificationError                  Traceback (most recent call last)
File [~/.pyenv/versions/3.9.18/lib/python3.9/site-packages/urllib3/connectionpool.py:467](http://localhost:8888/lab/tree/RTC%3ANuvisan/daptics-api/python_client/~/.pyenv/versions/3.9.18/lib/python3.9/site-packages/urllib3/connectionpool.py#line=466), in HTTPConnectionPool._make_request(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)
    466 try:
--> 467     self._validate_conn(conn)
    468 except (SocketTimeout, BaseSSLError) as e:

...

**Comment by nhpackard** [comment]
Upon trying to investigate in the docker container image, I found that there was no image.  
Maybe a more informative error message could get thrown in this case...

**Comment by anshalinsys** [comment]
I am facing the same issue 
do u find the solution for this
